books/urls.py
#books.urls
from django.urls import path
from .views import BooksListAPI,BooksDetailAPI

urlpatterns=[
    path('<int:pk>/', BooksDetailAPI.as_view(), name="book-detail-api"),
    path('', BooksListAPI.as_view(), name="book-list-api")
]

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# CRUD views
from books.views import (
    BookListView,
    BookDetailView,
    BookUpdateView,
    BookCreateView,
    BookDeleteView,
    BookDeleteConfirmView,
    BookUpdateConfirmView)

# authentication views
from books.views import (
    BookLogoutView,
    BookLoginView,
    SignUpView,
    LoggedinBookListView
    )

urlpatterns = [
    path('', BookListView.as_view(), name='book-list'), # list view used as home
    path('detail/<int:pk>/', BookDetailView.as_view(), name='book-detail'), # rember that to pass the primary key to the url here using <int:pk>
    path('create/', BookCreateView.as_view() ,name='book-create'),
    path('update/', BookUpdateView.as_view(), name='book-update'),
    path('update/confirm/<int:pk>/', BookUpdateConfirmView.as_view(), name='book-update-confirm'),
    path('delete/',BookDeleteView.as_view(), name='book-delete'),
    path('delete/confirm/<int:pk>/',BookDeleteConfirmView.as_view(), name='book-delete-confirm'),
    path('login/', BookLoginView.as_view(),name='login'),
    path('logout/', BookLogoutView.as_view(),name='logout'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('login/book-list/', LoggedinBookListView.as_view(), name='logged-in-book-list'),
    path('api/', include("books.urls")) #<- includes the urls file from the books app
]

# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/forms.py
from django import forms
from .models import Book
#from django.contrib.auth.forms import UserCreationForm

class CreateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'


class SelectBookForm(forms.Form):
    class Meta:
        model = Book
        book = forms.ModelChoiceField(
            queryset=Book.objects.all(),
            to_field_name='pk',  # Use the book's primary key as the field value
            label="Select a Book to Update"
        )


class UpdateBookForm(forms.ModelForm):
    class Meta:
        model = Book  # Associate the form with the Book model
        fields = ['id']  ##'__all__' You can specify specific fields if needed

        selected_book = forms.ModelChoiceField(
        queryset=Book.objects.all(),
        empty_label=None, # example to add label
        widget=forms.Select(attrs={'class': 'form-control'}))  # example to add widgets


class ConfirmBookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

    published_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'})) # this outputs a date widget in the template '{{update_form.published_date}}' if you include it it must be filled in!

"""
NOTE -from customisations
select fields 
    fields = ['title', 'author', 'published_date']

exlude fields
    exclude = ['published_date']  

customise widget 
    widgets = {
    'description': forms.Textarea(attrs={'rows': 4, 'cols': 40})}

custom validation
    def clean_title(self):
    # Custom validation for the 'title' field
    title = self.cleaned_data['title']
    if not title.isalnum():
    raise forms.ValidationError("Title should only contain alphanumeric characters.")
    return title

help text and labels
    labels = {'title': 'Book Title'}
    help_texts = {'author': 'The author of the book.'}

overriding the default form render to custom template
      template_name = 'custom_form_template.html'
"""

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} HTML Base Template  - Title goes here{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base-style.css' %}">
</head>
<body>

    <header>
        <h1>Django</h1>
        <nav>
            <ul>
                <li><a class="nav-text" href="/">List all Books</a></li>
                <li><a class="nav-text" href="/about/">About</a></li>
                <li><a class="nav-text" href="/contact/">Contact</a></li>

            </ul>
        </nav>
    </header>
    {%block header%}

    {%endblock header%}

    {% block content %}
    HTML Base Template - Content goes here
    {% endblock %}

    {%block footer%}
    <footer>
        <p>&copy; {{ current_year }} My Website</p>
        <p id="clock"></p>
    </footer>
    {%endblock footer%}

    <script>
        function updateClock() {
            const clock = document.getElementById("clock");
            const now = new Date();
            const hours = now.getHours().toString().padStart(2, "0");
            const minutes = now.getMinutes().toString().padStart(2, "0");
            const seconds = now.getSeconds().toString().padStart(2, "0");
            clock.textContent = `${hours}:${minutes}:${seconds}`;
        }

        setInterval(updateClock, 1000);
    </script>
</body>
</html>

templates/book-create-template.html
{% extends "base.html" %}

{%block header%}
    <h1>Bookstore</h1>
    <a href="{% url 'book-list' %}">Book List</a>
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'book-create' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

templates/book-delete-confirm-template.html
{% extends "base.html" %}

{% block header %}
    <h1>Bookstore</h1>
    <a href="{% url 'book-list' %}">See all Books</a>
{% endblock %}

<h2>Confirm deletion</h2>
<p>Are you sure you want to delete this book?</p>

{% block title %} Delete a book {% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="confirm" value="yes">Yes, confirm book deletion!</button>
        <a href="{% url 'book-list' %}">Cancel</a>
    </form>
{% endblock content %}

templates/book-delete-template.html
{% extends "base.html" %}

{% block header %}
    <h1>Bookstore</h1>
    <a href="{% url 'book-list' %}">Back to a list of all books</a>
{% endblock %}

{% block content %}
    <form method="post" action"">
        {% csrf_token %}
        <select name="book">
            {% for book in books %}
                <option value="{{ book.pk }}">{{ book.title }}</option>
            {% endfor %}
        </select>
        <button type="submit">Select</button>
    </form>
{% endblock content %}

templates/book-detail-template.html
<!-- FILEPATH: /home/dci-student/Desktop/Django/bookstore_django/templates/book-detail-template.html -->

{% extends 'base.html' %}

{% block header %}
    <h1>Bookstore</h1>
    <a href="{% url 'book-list' %}">See all Books in Stock</a>
{% endblock %}

{% block content %}
    <h1>{{ book_details.title }}</h1>
    <p>Author: {{ book_details.author }}</p>
    <p>Published: {{ book_details.published_date }}</p>
    <p>Price: £{{ book_details.price }}</p>
{% endblock %}

templates/book-list-template.html
{% extends "base.html" %}

{% block header %}
    <h1>Bookstore</h1>
    <a href="{% url 'book-create' %}">Add a new book</a><br>
    <a href="{% url 'book-delete' %}">Remove a sold book</a><br>
    <a href="{% url 'book-update' %}">Update and existing book</a>
{% endblock %}

{% block title %}List of Books{% endblock %}

{% block content %}
<ul>
    {% for book in books %}
        <li>
            <a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a>

        </li>
    {% endfor %}
</ul>
{% endblock %}

templates/book-update-confirm-template.html
{% extends "base.html" %}

{% block header %}
    <h1>Bookstore</h1>
    <a href="{% url 'book-list' %}">Back to a list of all books</a>
{% endblock %}

{% block content %}
    {% if selected_book %}
    <h2>Update Book: {{ selected_book.title }}</h2>
    <form method="post" action="">
        {% csrf_token %}
        <label for="title">Title:</label>
        <input type="text" name="title" value="{{ selected_book.title }}"><br>

        <label for="author">Author:</label>
        <input type="text" name="author" value="{{ selected_book.author }}"><br>

        <label for="description">Description:</label>
        <textarea name="description">{{ selected_book.description }}</textarea><br>

        <label for="price">Price:</label>
        <input type="number" name="price" value="{{ selected_book.price }}"><br>

        <label for="id_published_date">Published date:</label>
        <input type="text" name="published_date" id="published_date" value="{{ selected_book.published_date|date:'Y-m-d' }}"><br>
        <!-- {{update_form.published_date}} -->
        <button type="submit">Confirm Update</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
    {% else %}
    <form method="post" action="">
        {% csrf_token %}
        <select name="book">
            {% for book in books %}
                <option value="{{ book.pk }}">{{ book.title }}</option>
            {% endfor %}
        </select>
        <button type="submit">Select</button>
    </form>
    {% endif %}
{% endblock %}

templates/book-update-template.html
{% extends 'base.html' %}

{% block content %}
  <h2>Update Book</h2>

  <form method="post" action"" >
    {% csrf_token %}
    <select name="selected_book">
      {% for book in books %}
        <option value="{{ book.pk }}">{{ book.title }}</option>
      {% endfor %}
    </select>

    <button type="submit">Select Book to Update</button>
  </form>

  <a href="{% url 'book-list' %}">Back to Book List</a>
</div>
{% endblock %}

templates/logged-in-book-list-template.html
{% extends "base.html" %}

{% block header %}
    <h1>Bookstore</h1>
    {% if user.is_authenticated %}
        <p>Welcome {{user.username}}, nice to see you again!</p>
    {% endif %}
    <a href="{% url 'book-create' %}">Add a new book</a><br>
    <a href="{% url 'book-delete' %}">Remove a sold book</a><br>
    <a href="{% url 'book-update' %}">Update and existing book</a><br>
    <a href="{% url 'logout' %}">Logout</a>
{% endblock %}

{% block title %}List of Books{% endblock %}

{% block content %}
<ul>
    {% for book in books %}
        <li>
            <a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a>

        </li>
    {% endfor %}
</ul>
{% endblock %}

templates/login.html
{% extends "base.html" %}

<h2>Log in page</h2>

{% block content%}
<form action="" method="post">
    {% csrf_token%}
    {{form.as_p}}
    <button type="submit">Login</button><br>
    <a href="{% url 'sign-up' %}">Not registered yet? sign up here</a>
</form>
{% endblock content %}

templates/logout.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'book-list' %}">Return to the Book List</a>

    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}

templates/sign-up.html
{% extends "base.html" %}

<h2>Sign up</h2>


{% block content%}
<form action="" method="post">
    {% csrf_token%}
    {{form.as_p}}
    <button type="submit">Login</button>
</form>
{% endblock content %}